# Generated by Django 4.0.2 on 2022-02-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_few_cars'),
        ('data_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedtimescar',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
