# Generated by Django 4.0.2 on 2022-02-24 16:08

from django.db import migrations

def add_cars(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cars)
    ]
